name: Weekly Content Updates

on:
  workflow_dispatch

jobs:
  weeklycontentupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Set Updates apply Gist
      id: setUpdatedContent
      env:
        clearContent: ""
        ACTION_TOKEN: ${{ secrets.GH_ACTION }}
      run: |
        echo "NUG_RESPONSE=$(curl --no-progress-meter 'https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=%27owner%3Achrkqedek%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=5&semVerLevel=2.0.0')" >> "$GITHUB_OUTPUT"
        curl --no-progress-meter  -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTION_TOKEN" -H "X-Github-Api-Version: 2022-11-28" https://api.github.com/gists/14382e201fb6be671a33af3feae2c58d -d '{"description":"rssdata","files":{"test_gst.txt":{"content":"${{ steps.setUpdatedContent.outputs.NUG_RESPONSE }}" }}}'