name: Weekly Content Updates

on:
  workflow_dispatch

jobs:
  weeklycontentupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Get Content
      id: getContent
      run: |
        NUG_RESPONSE=$(curl 'https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=%27owner%3Achrkqedek%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=5&semVerLevel=2.0.0')
      env:
        NUGET_GEN: ${{ secrets.NUGET_GEN }}
    - name: Set Update
      id: setUpdatedContent
      run: |
        curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $(${{ secrets.NUGET_GEN }})" -H "X-Github-Api-Version: 2022-11-28" https://api.github.com/gists/14382e201fb6be671a33af3feae2c58d -d "{\"description\":\"rssdata\",\"files\":{\"xmlresp\":{\"content\":\"$NUG_RESPONSE\"}}}"