name: Weekly Content Updates

on:
  workflow_dispatch

jobs:
  weeklycontentupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Set updated content and parsing
      id: setUpdatedContent
      env:
        clearContent: ""
      run: |
        echo "NUG_RESPONSE<<EOF" >> $GITHUB_ENV
        echo "$(curl --no-progress-meter 'https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=%27owner%3Achrkqedek%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=5&semVerLevel=2.0.0')" >> $GITHUB_ENV
        echo $NUG_RESPONSE >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Upload to accesible Gist
      id: uploadToGist
      env:
        ACTION_TOKEN: ${{ secrets.GH_ACTION }}
        RESPONSE: "${{ env.NUG_RESPONSE }}"
      run: |
        curl --no-progress-meter  -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACTION_TOKEN" -H "X-Github-Api-Version: 2022-11-28" https://api.github.com/gists/14382e201fb6be671a33af3feae2c58d -d '{"description":"rssdata","files":{"test_gst.txt":{"content":\'${{ env.RESPONSE }}\'}}}'